name: projeto_integrador
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
 

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13 
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

 
  assets:
    - assets/images/
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  